env:
  node: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-underscore-dangle:  ["error", { "allow": ["__filename", "__dirname"] }]
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
 